### PR TITLE
Pretty xml

### PR DESCRIPTION
**Pull request by pfsk4tsh**

### CODE REVIEW

**Comment by pfsk4tsh** [comment]
Ah sorry, forgot to commit the new files.

**Comment by jurajsomorovsky** [comment]
Ok, I reconsidered my decision and think that this is not appropriate because we misuse XML structure and introduce a new XML level just to establish pretty printing. 

I will give you a different solution in a few minutes.

**Comment by jurajsomorovsky** [comment]
Please consider https://github.com/RUB-NDS/ModifiableVariable/tree/prettyXml2

What do you think?

**Comment by pfsk4tsh** [comment]
I agree. I'd prefer your solution, too. Adding a ByteArrayXmlType is not so nice

**Pull request closed without merging**
